# CI de Nivel 01 - Disparo manual a partir de 1 clique

name: 'Execução Manual'

# regras de disparo gatilhos/triggers
# gatilho de disparo manual = workflow_dispatch
# inputs = entradas que o usuário pode fornecer ao disparar o workflow manualmente

on:
  workflow_dispatch:

# jobs - tarefas que serão executadas
jobs:
  e2e-tests:
    #máquina virtual onde o job será executado
    runs-on: ubuntu-latest

    #passos do script de build
    steps:
        #clone do projeto
        - uses: actions/checkout@v4

        #instalação do Node.js
        - uses: actions/setup-node@v4
          with:
            node-version: latest

        #instalacao do yarn
        - name: Install Yarn
          run: npm install -g yarn

        #instalação das dependências
        - name: Install Dependencies
          run: yarn
        
        #instalacao do playwright
        - name: Install Playwright Browsers
          run: yarn playwright install
        
        #execucao dos testes e2e
        - name: Run E2E Tests
          run: yarn run e2e
