# CI de Nível 04 - Disparo dos testes dentro do pipe de dev

name: 'Execução Integrada'

on:
    workflow_dispatch:

jobs:
    inspecao:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install Dependencies
              run: yarn
            
            - name: Checando padronização de código
              run: yarn lint

    unidade:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install Dependencies
              run: yarn
            
            - name: Executando testes unitários
              run: yarn test
    e2e-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: latest

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install Dependencies
              run: yarn
            
            - name: Install Playwright Browsers
              run: yarn playwright install
            
            - name: Run E2E Tests
              run: yarn run e2e

            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: report
                path: ./playwright-report

    deploy:
        runs-on: ubuntu-latest

        needs: [inspecao, unidade, e2e-tests]

        steps:
            - uses: actions/checkout@v4

            - name: Simulação de Deploy
              run: echo "Deploying Simulator..."